[project]
authors = [
  {name = "foliant", email = "foliant@tutamail.com"},
]
dependencies = [
  "pydantic (>=2.13.4,<3.0.0)",
  "pydantic-settings (>=2.14.2,<3.0.0)",
  "fastapi (>=0.140.0,<0.141.0)",
  "openai (>=2.48.0,<3.0.0)",
  "pandas (>=3.0.5,<4.0.0)",
  "uvicorn (>=0.51.0,<0.52.0)",
]
description = ""
name = "agent"
requires-python = ">=3.13"
version = "0.1.0"

[tool.poetry]
packages = [
  {include = "app"},
]

[tool.poetry.scripts]
start = "app.main:run"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]

[dependency-groups]
dev = [
  "pytest (>=9.1.1,<10.0.0)",
]
